# Generated by Django 5.2 on 2025-05-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='customer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='exp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='projects',
            field=models.IntegerField(),
        ),
    ]
